name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: build

      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
            BRANCH: gh-pages
            FOLDER: build
