name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Setup node'
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'Install dependencies'
        run: yarn

      - name: 'Test'
        run: yarn test

      - name: 'Build'
        env:
          NODE_ENV: production
        run: yarn build

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
