name: Test & Build & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Setup node'
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'Install dependencies'
        run: yarn

  test:
    runs-on: ubuntu-latest
    needs:
      prepare

    steps:
      - uses: actions/checkout@v2
      - name: 'Tests'
        run: yarn test

  build:
    runs-on: ubuntu-latest
    needs:
      prepare
    env:
      NODE_ENV: production

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: yarn build
